sources:
  - name: reference
    tables:
      - name: full_moon_dates
        identifier: raw_full_moon_dates
  - name: raw_listings
    schema: j9r-kafka
    tables:
      - name: raw_listings
    config:
      contract:
        enforced: true

  - name: raw_hosts
    schema: j9r-kafka
    tables:
      - name: raw_hosts
        columns:
          - name: host_id
            data_type: string
          - name: host_name
            data_type: string
          - name: is_superhost
            data_type: boolean
          - name: created_at
            data_type: string
          - name: updated_at
            data_type: string
    config:
      contract:
        enforced: true
  - name: raw_reviews
    schema: j9r-kafka
    tables:
      - name: raw_reviews
    config:
      contract:
        enforced: true
