sources:
  - name: reference
    tables:
      - name: full_moon_dates
        identifier: raw_full_moon_dates
  - name: raw_listings
    schema: j9r-kafka
    tables:
      - name: raw_listings
        columns:
        - name: listing_id
          data_type: string
        - name: listing_url
          data_type: string
        - name: listing_name
          data_type: string
        - name: room_type
          data_type: string
        - name: minimum_nights
          data_type: int
        - name: host_id
          data_type: string
        - name: price_str
          data_type: string
        - name: price
          data_type: double
        - name: created_at
          data_type: string
        - name: updated_at
          data_type: string
    config:
      contract:
        enforced: true

  - name: raw_hosts
    schema: j9r-kafka
    tables:
      - name: raw_hosts
        columns:
          - name: host_id
            data_type: string
          - name: host_name
            data_type: string
          - name: is_superhost
            data_type: boolean
          - name: created_at
            data_type: string
          - name: updated_at
            data_type: string
    config:
      contract:
        enforced: true
  - name: raw_reviews
    schema: j9r-kafka
    tables:
      - name: raw_reviews
        columns:
          - name: listing_id
            data_type: string
          - name: date
            data_type: string
          - name: reviewer_name
            data_type: string
          - name: comments
            data_type: string
          - name: sentiment
            data_type: string
    config:
      contract:
        enforced: true
