
# Internal ClusterIP Service for ingress and internal access
apiVersion: v1
kind: Service
metadata:
  name: producer-api-service
  namespace: rental
  labels:
    name: rental-demo
    app: json-xform
    component: api-server
spec:
  selector:
    name: rental-demo
    app: json-xform
    component: api-server
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
---
# NodePort Service for direct localhost access
apiVersion: v1
kind: Service
metadata:
  name: producer-api-nodeport
  namespace: rental
  labels:
    name: rental-demo
    app: json-xform
    component: api-server
spec:
  selector:
    name: rental-demo
    app: json-xform
    component: api-server
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
  type: NodePort
---
# Optional: Ingress for external access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: producer-api-ingress
  namespace: rental
  labels:
    name: rental-demo
    app: json-xform
    component: api-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
spec:
  ingressClassName: nginx
  rules:
  - host: producer-api.local  # Update this to your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: producer-api-service
            port:
              number: 80
