version: 2
models:
- name: employee_count
  description: Migrated from dml.employee_count.sql
  columns:
  - name: dept_id
    data_type: INT
    constraints:
      - type: not_null
      - type: primary_key
        expression: "not enforced"
  - name: emp_count
    data_type: BIGINT
