apiVersion: v1
kind: Pod
metadata:
  name: dedup-demo-producer
  namespace: confluent
  labels:
    app: dedup-demo
    component: producer
spec:
  restartPolicy: Never
  containers:
  - name: producer
    image: dedup-demo-producer:latest
    imagePullPolicy: IfNotPresent
    envFrom:
    - configMapRef:
        name: dedup-demo-config
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    livenessProbe:
      exec:
        command:
        - python
        - -c
        - "import confluent_kafka, pydantic; print('Dependencies OK')"
      initialDelaySeconds: 10
      periodSeconds: 60 