apiVersion: cmf.confluent.io/v1alpha1
kind: FlinkApplication
metadata: 
  name: ecom-flink-app
  namespace: flink
spec:
  image: jbcodeforce/ecom-flink-app:0.1.0
  flinkVersion: v1_19
  imagePullPolicy: Never
  serviceAccount: flink
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: '1'
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          envFrom:
            - configMapRef:
                name: flink-app-cm
  job: 
      jarURI: local:///opt/flink/usrlib/flink-app-ecom-0.1.0.jar
      parallelism: 1
      upgradeMode: stateless
      state: running
  jobManager: 
    resource: 
      cpu: 1
      memory: 1048m
  taskManager: 
    resource: 
      cpu: 1
      memory: 1048m