apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata: 
  name: ecom-flink
  namespace: flink
spec:
  flinkConfiguration: 
    metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
    metrics.reporter.prom.port: 9249-9250
    taskmanager.numberOfTaskSlots: 1
  flinkVersion: v1_19
  image: confluentinc/cp-flink:1.19.1-cp1
  imagePullPolicy: Never
  serviceAccount: flink
  job: 
      jarURI: flink-app/target/flink-app-ecom-0.1.0.jar
      parallelism: 1
      upgradeMode: stateless
  jobManager: 
    resource: 
    cpu: 1
    memory: 1048m
  taskManager: 
    resource: 
    cpu: 1
    memory: 1048m