{
 "title": "CC Flink Example Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "compute_pools", "label": "Compute Pool(s)", "query": { "query": "label_values(compute_pool_id)" } },
   {
    "name": "statements",
    "label": "Statement(s)",
    "query": {
     "query": "label_values(confluent_flink_statement_status, flink_statement_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CFU Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Compute Pools",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (group by (compute_pool_id) (confluent_flink_compute_pool_utilization_current_cfus))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Utilization per Compute Pool",
   "type": "timeseries",
   "description": "% utilization per compute pool, meaning the current CFU consumption divided by the compute pool limit",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "confluent_flink_compute_pool_utilization_current_cfus{compute_pool_id=~\"$compute_pools\"} / confluent_flink_compute_pool_utilization_cfu_limit{compute_pool_id=~\"$compute_pools\"}",
     "legendFormat": "{{compute_pool_id}}"
    }
   ]
  },
  {
   "title": "Total Current CFUs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_flink_compute_pool_utilization_current_cfus)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CFU Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(confluent_flink_compute_pool_utilization_cfu_limit)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Statement Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Number of Statements by Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(status) (confluent_flink_statement_status{compute_pool_id=~\"$compute_pools\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(vector(0), \"status\", \"DEGRADED\", \"\", \"\") unless count(confluent_flink_statement_status{status=\"DEGRADED\", compute_pool_id=~\"$compute_pools\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "List of Non-Terminal Statements",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "confluent_flink_statement_status{status!~\"COMPLETED|FAILED\", compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statements per Status over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "count by (status) (confluent_flink_statement_status{compute_pool_id=~\"$compute_pools\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(vector(0), \"status\", \"DEGRADED\", \"\", \"\") unless count(confluent_flink_statement_status{status=\"DEGRADED\", compute_pool_id=~\"$compute_pools\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Statement Lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Max Pending Records",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(confluent_flink_pending_records{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Input Lateness",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(confluent_flink_max_input_lateness_milliseconds{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Output Watermark Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(clamp_min((time() * 1000 - confluent_flink_current_output_watermark_milliseconds{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}) and (confluent_flink_current_output_watermark_milliseconds{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"} > 946684800000), 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Input Watermark Lag",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(clamp_min((time() * 1000 - confluent_flink_current_input_watermark_milliseconds{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}) and (confluent_flink_current_input_watermark_milliseconds{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"} > 946684800000), 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Records (Backlog)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "confluent_flink_pending_records{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}",
     "legendFormat": "{{flink_statement_name}}"
    }
   ]
  },
  {
   "title": "Max Input Lateness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "confluent_flink_max_input_lateness_milliseconds{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}",
     "legendFormat": "{{flink_statement_name}}"
    }
   ]
  },
  {
   "title": "Output Watermark Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "clamp_min((time() * 1000 - confluent_flink_current_output_watermark_milliseconds{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}) and (confluent_flink_current_output_watermark_milliseconds{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"} > 946684800000), 0)",
     "legendFormat": "{{flink_statement_name}}"
    }
   ]
  },
  {
   "title": "Input Watermark Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "clamp_min((time() * 1000 - confluent_flink_current_input_watermark_milliseconds{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}) and (confluent_flink_current_input_watermark_milliseconds{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"} > 946684800000), 0)",
     "legendFormat": "{{flink_statement_name}}"
    }
   ]
  },
  {
   "title": "Statement Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "CFUs Used per Statement",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "confluent_flink_statement_utilization_current_cfus{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}",
       "legendFormat": "{{flink_statement_name}}"
      }
     ]
    },
    {
     "title": "Messages Behind per Statement",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "confluent_flink_pending_records{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}",
       "legendFormat": "{{flink_statement_name}}"
      }
     ]
    },
    {
     "title": "Messages In per Statement",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "confluent_flink_num_records_in{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}",
       "legendFormat": "{{flink_statement_name}}"
      }
     ]
    },
    {
     "title": "Messages Out per Statement",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "confluent_flink_num_records_out{compute_pool_id=~\"$compute_pools\", flink_statement_name=~\"$statements\"}",
       "legendFormat": "{{flink_statement_name}}"
      }
     ]
    }
   ]
  }
 ]
}