
with relevant_records as (
-- demonstrate data filtering with CTE
select
  *,
  $rowtime as ts
  from `prod.mvwms.WM410BASD.PLPULL00.v1`  where headers.operation <> 'REFRESH' and (not (data is null and beforeData is null))
),
extracted_data as (
 SELECT 
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPLN, data.PLPLN), 'NULL') as PLPLN,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLWHSE, data.PLWHSE), 'NULL') as PLWHSE,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPLD, data.PLPLD), 'NULL') as PLPLD,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLLFID, data.PLLFID), 'NULL') as PLLFID,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLCRT, data.PLCRT), 'NULL') as PLCRT,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLRPTY, data.PLRPTY), 'NULL') as PLRPTY,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLRBCH, data.PLRBCH), 'NULL') as PLRBCH,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLRCTP, data.PLRCTP), 'NULL') as PLRCTP,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTSKG, data.PLTSKG), 'NULL') as PLTSKG,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTIME, data.PLTIME), 0) as PLTIME,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLESDT, data.PLESDT), 0) as PLESDT,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLESTM, data.PLESTM), 0) as PLESTM,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLEEDT, data.PLEEDT), 0) as PLEEDT,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLEETM, data.PLEETM), 0) as PLEETM,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLASDT, data.PLASDT), 0) as PLASDT,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLASTM, data.PLASTM), 0) as PLASTM,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLAEDT, data.PLAEDT), 0) as PLAEDT,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLAETM, data.PLAETM), 0) as PLAETM,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLBGAR, data.PLBGAR), 'NULL') as PLBGAR,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLBGZN, data.PLBGZN), 'NULL') as PLBGZN,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLBGAL, data.PLBGAL), 'NULL') as PLBGAL,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLEDAR, data.PLEDAR), 'NULL') as PLEDAR,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLEDZN, data.PLEDZN), 'NULL') as PLEDZN,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLEDAL, data.PLEDAL), 'NULL') as PLEDAL,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLSCWG, data.PLSCWG), 'NULL') as PLSCWG,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLSCWA, data.PLSCWA), 'NULL') as PLSCWA,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLECWG, data.PLECWG), 'NULL') as PLECWG,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLECWA, data.PLECWA), 'NULL') as PLECWA,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLSDWG, data.PLSDWG), 'NULL') as PLSDWG,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLSDWA, data.PLSDWA), 'NULL') as PLSDWA,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLEDWG, data.PLEDWG), 'NULL') as PLEDWG,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLEDWA, data.PLEDWA), 'NULL') as PLEDWA,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPKLC, data.PLPKLC), 'NULL') as PLPKLC,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTSTY, data.PLTSTY), 'NULL') as PLTSTY,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLCRIN, data.PLCRIN), 'NULL') as PLCRIN,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTXST, data.PLTXST), 'NULL') as PLTXST,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTXSQ, data.PLTXSQ), 'NULL') as PLTXSQ,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTSKC, data.PLTSKC), 'NULL') as PLTSKC,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPRCD, data.PLPRCD), 'NULL') as PLPRCD,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPRFN, data.PLPRFN), 'NULL') as PLPRFN,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLASND, data.PLASND), 'NULL') as PLASND,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLNDID, data.PLNDID), 'NULL') as PLNDID,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLSTAT, data.PLSTAT), 'NULL') as PLSTAT,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPRSQ, data.PLPRSQ), 0) as PLPRSQ,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPRDT, data.PLPRDT), 0) as PLPRDT,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPLSQ, data.PLPLSQ), 0) as PLPLSQ,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLNDLC, data.PLNDLC), 'NULL') as PLNDLC,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLSHTP, data.PLSHTP), 'NULL') as PLSHTP,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLLDSQ, data.PLLDSQ), 0) as PLLDSQ,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLOTY, data.PLOTY), 'NULL') as PLOTY,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTRIG, data.PLTRIG), 'NULL') as PLTRIG,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLRSCD, data.PLRSCD), 'NULL') as PLRSCD,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLSHDS, data.PLSHDS), 'NULL') as PLSHDS,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLVNAF, data.PLVNAF), 'NULL') as PLVNAF,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLOSTS, data.PLOSTS), 'NULL') as PLOSTS,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPLAN, data.PLPLAN), 'NULL') as PLPLAN,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLBRKL, data.PLBRKL), 'NULL') as PLBRKL,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLREPL, data.PLREPL), 'NULL') as PLREPL,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPICT, data.PLPICT), 'NULL') as PLPICT,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPKTL, data.PLPKTL), 'NULL') as PLPKTL,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLWWTN, data.PLWWTN), 'NULL') as PLWWTN,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLASUS, data.PLASUS), 'NULL') as PLASUS,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLASTG, data.PLASTG), 'NULL') as PLASTG,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLSPLT, data.PLSPLT), 'NULL') as PLSPLT,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLSKPD, data.PLSKPD), 'NULL') as PLSKPD,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLHOTW, data.PLHOTW), 'NULL') as PLHOTW,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLCMTK, data.PLCMTK), 'NULL') as PLCMTK,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLORST, data.PLORST), 'NULL') as PLORST,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLWRTP, data.PLWRTP), 'NULL') as PLWRTP,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLWRID, data.PLWRID), 'NULL') as PLWRID,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLCOST, data.PLCOST), 0) as PLCOST,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLOTKG, data.PLOTKG), 'NULL') as PLOTKG,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTCTM, data.PLTCTM), 0) as PLTCTM,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTCTG, data.PLTCTG), 'NULL') as PLTCTG,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLMIS1, data.PLMIS1), 'NULL') as PLMIS1,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLMIS2, data.PLMIS2), 'NULL') as PLMIS2,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLNUM1, data.PLNUM1), 0) as PLNUM1,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLRCEX, data.PLRCEX), 'NULL') as PLRCEX,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLCREX, data.PLCREX), 'NULL') as PLCREX,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLPKID, data.PLPKID), 'NULL') as PLPKID,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLDCR, data.PLDCR), 0) as PLDCR,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTCR, data.PLTCR), 0) as PLTCR,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLDLM, data.PLDLM), 0) as PLDLM,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLTLM, data.PLTLM), 0) as PLTLM,
coalesce(if(headers.operation in ('DELETE'), beforeData.PLUSER, data.PLUSER), 'NULL') as PLUSER,
ts
from relevant_records)
select
 * 
 from (
  select *,  ROW_NUMBER() OVER (
          PARTITION BY PLPLN
          ORDER
            BY ts DESC
        ) AS row_num from extracted_data
  ) where row_num = 1;