[project]
name = "flink-studies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.10",
    "mkdocs-minify-plugin>=0.8.0",
    "mkdocstrings>=0.29.0",
]
