apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: employee-count
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
