apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  dataVolumeCapacity: 10G
  image:
    application: docker.io/confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  replicas: 1
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
  labels:
    app: kafka
spec:
  configOverrides:
    server:
      # The in-built HTTP server for the REST proxy sometimes takes time to start up, and the broker kills itself if
      # it doesn't start within the timeout. So we increase the timeout to 5 minutes.
      - confluent.http.server.start.timeout.ms=300000
  replicas: 1
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  dataVolumeCapacity: 20Gi
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  namespace: confluent
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30092
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: in
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 1
  kafkaClusterRef:
    name: kafka
    namespace: confluent
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: out
  namespace: confluent
spec:
    replicas: 1
    partitionCount: 1
    kafkaClusterRef:
        name: kafka
        namespace: confluent
