apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
  namespace: flink-cdc
  labels:
    app: flink-cdc
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: blob-server
    port: 6124
  - name: webui
    port: 8081
  selector:
    app: flink-cdc
    component: jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager-rest
  namespace: flink-cdc
  labels:
    app: flink-cdc
spec:
  type: NodePort
  ports:
  - name: rest
    port: 8081
    targetPort: 8081
    nodePort: 30081
  selector:
    app: flink-cdc
    component: jobmanager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: flink-cdc
  labels:
    app: flink-cdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-cdc
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink-cdc
        component: jobmanager
    spec:
      initContainers:
      - name: download-connectors
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Downloading Flink Kafka connector JARs..."
            cd /opt/flink/lib
            # Kafka connector
            curl -sLO https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.2.0-1.19/flink-sql-connector-kafka-3.2.0-1.19.jar
            # JSON format (included in Flink, but ensure we have it)
            curl -sLO https://repo1.maven.org/maven2/org/apache/flink/flink-json/1.20.1/flink-json-1.20.1.jar
            echo "Downloaded connector JARs:"
            ls -la /opt/flink/lib/*.jar
        volumeMounts:
        - name: flink-lib
          mountPath: /opt/flink/lib
      containers:
      - name: jobmanager
        image: apache/flink:1.20.1-scala_2.12
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob-server
        - containerPort: 8081
          name: webui
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: flink-lib
          mountPath: /opt/flink/lib
        securityContext:
          runAsUser: 9999
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-cdc-config
          items:
          - key: config.yaml
            path: config.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      - name: flink-lib
        emptyDir: {}
