apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: flink-cdc
  labels:
    app: flink-cdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-cdc
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink-cdc
        component: taskmanager
    spec:
      initContainers:
      - name: download-connectors
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Downloading Flink Kafka connector JARs..."
            cd /opt/flink/lib
            # Kafka connector
            curl -sLO https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.2.0-1.19/flink-sql-connector-kafka-3.2.0-1.19.jar
            # JSON format
            curl -sLO https://repo1.maven.org/maven2/org/apache/flink/flink-json/1.20.1/flink-json-1.20.1.jar
            echo "Downloaded connector JARs:"
            ls -la /opt/flink/lib/*.jar
        volumeMounts:
        - name: flink-lib
          mountPath: /opt/flink/lib
      containers:
      - name: taskmanager
        image: apache/flink:1.20.1-scala_2.12
        args: ["taskmanager"]
        ports:
        - containerPort: 6122
          name: rpc
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf/
        - name: flink-lib
          mountPath: /opt/flink/lib
        securityContext:
          runAsUser: 9999
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-cdc-config
          items:
          - key: config.yaml
            path: config.yaml
          - key: log4j-console.properties
            path: log4j-console.properties
      - name: flink-lib
        emptyDir: {}
