apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: perf-output
  namespace: kafka
spec:
  kafkaRestClassRef:
    name: default
    namespace: kafka
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "delete"