apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-csv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual # Must match the PV's storageClassName
  resources:
    requests:
      storage: 1Gi # Request the same or less storage than the PV