[project]
name = "dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
     "dagster-dbt>=0.28.14",
     "dagster-webserver>=1.12.14",
     "dbt-autofix>=0.20.0",
     "dbt-confluent>=0.3.0",
     "confluent-sql>=0.4.0",
     "dbt-core>=1.11.12",
     "dbt-duckdb>=1.10.1",
     "dbt-snowflake>=1.11.2",
     "confluent-kafka>=2.6.0",
     "authlib>=1.6.5",
     "cachetools>=6.2.1",
     "typer>=0.15.0",
     "pyyaml>=6.0.2",
     "pydantic>=2.11.0",
]
