apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: orders
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
  kafkaClusterRef:
    name: kafka
