apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: el-demo
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    http_port = 3000
    root_url = http://localhost:3000/
    
    [security]
    admin_user = admin
    admin_password = admin123
    allow_embedding = true
    
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer
    
    [dashboards]
    default_home_dashboard_path = /etc/grafana/provisioning/dashboards/external-lookup-dashboard.json
    
    [log]
    level = info
    
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: true
        
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'External Lookup Dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /etc/grafana/provisioning/dashboards

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-config
  namespace: el-demo
  labels:
    app: grafana
data:
  external-lookup-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "collapsed": false,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "panels": [],
          "title": "External Lookup Application Overview",
          "type": "row"
        }
      ],
      "refresh": "30s",
      "schemaVersion": 37,
      "style": "dark",
      "tags": [
        "flink",
        "kafka",
        "external-lookup",
        "claims"
      ],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "el-demo",
              "value": "el-demo"
            },
            "hide": 0,
            "includeAll": false,
            "multi": false,
            "name": "namespace",
            "options": [
              {
                "selected": true,
                "text": "el-demo",
                "value": "el-demo"
              }
            ],
            "query": "el-demo",
            "queryValue": "",
            "skipUrlSync": false,
            "type": "textbox"
          }
        ]
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "External Lookup Application Dashboard",
      "uid": "external-lookup-dashboard",
      "version": 1,
      "weekStart": ""
    }
