apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: pgdb
---

apiVersion: v1
data:
  username: YXBw
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: app-secret
  namespace: pgdb
type: kubernetes.io/basic-auth
---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: pgdb
spec:
  instances: 1

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret

  storage:
    size: 1Gi
  
  additionalVolumes:
    - name: data-files
      persistentVolumeClaim:
        claimName: data-files-pvc
  
  additionalVolumeMounts:
    - name: data-files
      mountPath: /data-files
      readOnly: true
  