apiVersion: v1
kind: Namespace
metadata:
  name: external-lookup
  labels:
    name: external-lookup
    app: payment-claims-enrichment
    environment: dev
  annotations:
    description: "Namespace for external lookup demo components"
