apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: order-details
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  replicas: 1
  partitionCount: 1
  configs:
    cleanup.policy: "delete"
    retention.ms: "86400000" # 24 hours