apiVersion: platform.confluent.io/v1beta1
kind: Schema
metadata:
  name: employee-count-value
  namespace: confluent
spec:
  schemaRegistryClusterRef:
    name: schemaregistry
    namespace: confluent
  data:
    configRef: employee-count-value
    format: json
  compatibilityLevel: BACKWARD
