apiVersion: v1
kind: Secret
metadata:
  name: claimdb-secret
  namespace: el-demo
  labels:
    app: external-lookup
    component: database
type: Opaque
stringData:
  DB_USER: "claims_user"
  DB_PASSWORD: "claims_password"  # Change this in production
