apiVersion: apps/v1
kind: Deployment
metadata:
  name: duckdb-external-lookup
  namespace: duckdb
  labels:
    app: duckdb-external-lookup
    component: database
spec:
  replicas: 1  # DuckDB is single-node, no replication
  selector:
    matchLabels:
      app: duckdb-external-lookup
      component: database
  template:
    metadata:
      labels:
        app: duckdb-external-lookup
        component: database
    spec:
      containers:
      - name: duckdb-api
        image: duckdb-external-lookup:latest
        imagePullPolicy: IfNotPresent  # Use local image for development
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: duckdb-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
        volumeMounts:
        - name: duckdb-data
          mountPath: /data
        - name: init-logs
          mountPath: /app/logs
      volumes:
      - name: duckdb-data
        persistentVolumeClaim:
          claimName: duckdb-pvc
      - name: init-logs
        emptyDir: {}
      restartPolicy: Always
      # Security context for non-root container
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534  # nobody user
        runAsGroup: 65534
        fsGroup: 65534

---
# Persistent Volume Claim for DuckDB database file
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duckdb-pvc
  namespace: duckdb
  labels:
    app: duckdb-external-lookup
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # No storageClassName for manual binding to pre-created PV
