apiVersion: v1
kind: PersistentVolume
metadata:
  name: duckdb-pv
  labels:
    app: __APP_NAME__
    component: storage
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Keep data when PVC is deleted
  # No storageClassName for manual binding to specific PVC
  hostPath:
    path: __DATABASE_DATA_PATH__  # Will be substituted with actual path
    type: Directory  # Directory must exist (contains the database file)
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
          - darwin  # macOS for Colima
