apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: sql-demo
spec:
  image: j9r/flink-sql-runner:latest
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/sql-runner.jar
    args: ["/opt/flink/usrlib/sql-scripts/main.sql"]
    parallelism: 1
    upgradeMode: stateless