apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
      - name: debezium
        image: quay.io/debezium/connect:2.5
        ports:
        - containerPort: 8083
        env:
        - name: BOOTSTRAP_SERVERS
          value: kafka-kafka-brokers.default.svc.cluster.local:9092
        - name: GROUP_ID
          value: debezium-connectors
        - name: CONFIG_STORAGE_TOPIC
          value: debezium-config
        - name: OFFSET_STORAGE_TOPIC
          value: debezium-offsets
        - name: STATUS_STORAGE_TOPIC
          value: debezium-status
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: debezium-service

---
apiVersion: v1
kind: Service
metadata:
  name: debezium-service
spec:
  selector:
    app: debezium
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP
