apiVersion: v1
kind: Secret
metadata:
  name: debezium-secret
  namespace: confluent
type: Opaque
stringData:
  username: app
  password: apppwd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connect-role
  namespace: confluent
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["debezium-secret"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connect-role-binding
  namespace: confluent
subjects:
  - kind: ServiceAccount
    name: connect-service-account
    namespace: confluent
roleRef:
  kind: Role
  name: connect-role
  namespace: confluent
  apiGroup: rbac.authorization.k8s.io

