apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: pgdb
---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: pgdb
type: Opaque
stringData:
  username: app
  password: apppwd

---

apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
  namespace: pgdb
spec:
  instances: 1

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-secret

  storage:
    size: 1Gi