# Flink JobManager Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: flink
  labels:
    app: payment-claims-enrichment
    component: jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-claims-enrichment
      component: jobmanager
  template:
    metadata:
      labels:
        app: payment-claims-enrichment
        component: jobmanager
    spec:
      serviceAccountName: flink-service-account
      containers:
      - name: jobmanager
        image: apache/flink:1.20.0-scala_2.12-java11
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 6124
          name: blob-server
        - containerPort: 8081
          name: webui
        - containerPort: 9249
          name: metrics
        command:
        - /opt/flink/bin/standalone-job.sh
        - start-foreground
        - --job-classname=com.example.PaymentClaimsEnrichment
        env:
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: flink-jobmanager
            jobmanager.rpc.port: 6123
            jobmanager.memory.process.size: 1600m
            taskmanager.memory.process.size: 1728m
            taskmanager.numberOfTaskSlots: 2
            parallelism.default: 1
        envFrom:
        - configMapRef:
            name: payment-claims-enrichment-config
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: flink-app-jar
          mountPath: /opt/flink/usrlib
        - name: checkpoints
          mountPath: /opt/flink/checkpoints
        - name: savepoints
          mountPath: /opt/flink/savepoints
        resources:
          requests:
            memory: "1600Mi"
            cpu: "0.5"
          limits:
            memory: "2048Mi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /config
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /config
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
      - name: flink-app-jar
        emptyDir: {}
      - name: checkpoints
        persistentVolumeClaim:
          claimName: flink-checkpoints
      - name: savepoints
        persistentVolumeClaim:
          claimName: flink-savepoints
      initContainers:
      - name: jar-downloader
        image: curlimages/curl:8.5.0
        command:
        - sh
        - -c
        - |
          # In a real deployment, you'd download from your registry or artifact repository
          echo "Copying application JAR..."
          # This is a placeholder - in practice you'd copy from a volume or download
          touch /opt/flink/usrlib/payment-claims-enrichment-1.0-SNAPSHOT.jar
        volumeMounts:
        - name: flink-app-jar
          mountPath: /opt/flink/usrlib

---
# Flink TaskManager Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  namespace: flink
  labels:
    app: payment-claims-enrichment
    component: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-claims-enrichment
      component: taskmanager
  template:
    metadata:
      labels:
        app: payment-claims-enrichment
        component: taskmanager
    spec:
      serviceAccountName: flink-service-account
      containers:
      - name: taskmanager
        image: apache/flink:1.20.0-scala_2.12-java11
        ports:
        - containerPort: 6122
          name: rpc
        - containerPort: 6125
          name: query-state
        - containerPort: 9249
          name: metrics
        command:
        - /opt/flink/bin/taskmanager.sh
        - start-foreground
        env:
        - name: FLINK_PROPERTIES
          value: |
            jobmanager.rpc.address: flink-jobmanager
            taskmanager.numberOfTaskSlots: 2
            taskmanager.memory.process.size: 1728m
        envFrom:
        - configMapRef:
            name: payment-claims-enrichment-config
        volumeMounts:
        - name: flink-config-volume
          mountPath: /opt/flink/conf
        - name: flink-app-jar
          mountPath: /opt/flink/usrlib
        - name: checkpoints
          mountPath: /opt/flink/checkpoints
        - name: savepoints
          mountPath: /opt/flink/savepoints
        resources:
          requests:
            memory: "1728Mi"
            cpu: "0.5"
          limits:
            memory: "2048Mi"
            cpu: "1"
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: flink-config-volume
        configMap:
          name: flink-config
      - name: flink-app-jar
        emptyDir: {}
      - name: checkpoints
        persistentVolumeClaim:
          claimName: flink-checkpoints
      - name: savepoints
        persistentVolumeClaim:
          claimName: flink-savepoints
      initContainers:
      - name: jar-downloader
        image: curlimages/curl:8.5.0
        command:
        - sh
        - -c
        - |
          echo "Copying application JAR..."
          touch /opt/flink/usrlib/payment-claims-enrichment-1.0-SNAPSHOT.jar
        volumeMounts:
        - name: flink-app-jar
          mountPath: /opt/flink/usrlib
