apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-sa
  namespace: el-demo
  labels:
    app: external-lookup
    component: rbac

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flink-cluster-role
  labels:
    app: external-lookup
    component: rbac
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale", "replicasets"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
- apiGroups: ["extensions"]
  resources: ["deployments", "deployments/scale", "replicasets"]
  verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flink-cluster-role-binding
  labels:
    app: external-lookup
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flink-cluster-role
subjects:
- kind: ServiceAccount
  name: flink-sa
  namespace: el-demo


