apiVersion: batch/v1
kind: Job
metadata:
  name: perf-producer
  labels:
    app: perf-producer
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: perf-producer
    spec:
      restartPolicy: Never
      containers:
        - name: producer
          image: perf-data-generator:0.1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: perf-producer-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
