apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink-operator
  namespace: flink-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-to-sa
subjects:
  - kind: ServiceAccount
    name: flink-operator
    namespace: flink-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin