scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: false
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: YOUR_METRICS_API_KEY_ID
      password: YOUR_METRICS_API_KEY_SECRET
    metrics_path: /v2/metrics/cloud/export
    params:
      "resource.kafka.id":
        - lkc-EXAMPLE
      "resource.schema_registry.id":
        - lsrc-EXAMPLE
      "resource.compute_pool.id":
        - lfcp-EXAMPLE
        - lfcp-EXAMPLE2
