scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: false
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: ZSU4RQZJWEABI6IB
      password: cfltj0sLxaUnj9YHqvfJ5AQOathr8aSI1I8mmp4CI1EguJ2ZB9Stx5NggIjChaYw
    metrics_path: /v2/metrics/cloud/export
    params:
      "resource.kafka.id":
        - lkc-7v233w
      "resource.schema_registry.id":
        - lsrc-3oxyv2
      "resource.compute_pool.id":
        - lfcp-11p88z
        - lfcp-n7jzzz
