apiVersion: batch/v1
kind: Job
metadata:
  name: insert-cars
  namespace: pgdb
spec:
  template:
    spec:
      containers:
      - name: insert-cars
        image:  ghcr.io/cloudnative-pg/postgresql:17.4
        command: ["psql", "-h", "pg-cluster-rw", "-U", "app", "-d", "app", "-f", "/tmp/insert_car_records.sql"]
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
        volumeMounts:
        - name: table-script
          mountPath: /tmp
      restartPolicy: Never
      volumes:
      - name: table-script
        configMap:
          name: create-cars-table-cm
  backoffLimit: 1 # Set to 1 to run the job once
  completionMode: "Indexed" 