# Generated by Terraform — do not commit
PROMETHEUS_CC_METRICS_API_KEY=${metrics_api_key_id}
PROMETHEUS_CC_METRICS_API_SECRET=${metrics_api_key_secret}
KAFKA_CLUSTER_ID=${kafka_cluster_id}
SCHEMA_REGISTRY_ID=${schema_registry_id}
FLINK_COMPUTE_POOL_IDS=${compute_pool_ids}
PROMETHEUS_EXPORT_HOST=api.telemetry.confluent.cloud
