CREATE TABLE IF NOT EXISTS staging_cdc_marqeta_jcard_tranlog_history (
    __jetstream__prg_id STRING,
    __jetstream__shard_id STRING,
    __jetstream__entry_createdate TIMESTAMP(3),
    __jetstream__deleted BOOLEAN,
    __jetstream__loaded_at TIMESTAMP(3),
    __jetstream__source_ts TIMESTAMP(3),
    __jetstream__transaction_id STRING,
    __jetstream__gtid STRING,
    __jetstream__offset STRING,
    __jetstream__partition INTEGER,
    __jetstream__key STRING,
    __jetstream__ts TIMESTAMP(3),
    __jetstream__total_order INTEGER,
    __jetstream__data_collection_order INTEGER,
    __jetstream__source_name STRING,
    __jetstream__source_db STRING,
    __jetstream__source_table STRING,
    __jetstream__server_uuid STRING,
    __jetstream__server_transaction_id INTEGER,
    __jetstream__op STRING,
    __jetstream__snapshot BOOLEAN,
    ca_street STRING,
    response STRING,
    transactionState STRING,
    reversalCount DECIMAL(38, 0),
    retrievalReferenceNumber STRING,
    irc STRING,
    displayMessage STRING,
    glTransaction DECIMAL(38, 0),
    refId DECIMAL(38, 0),
    networkReferenceId STRING,
    voidCount DECIMAL(38, 0),
    issuerFee DECIMAL(38, 4),
    voidId DECIMAL(38, 0),
    createdTime TIMESTAMP(3),
    actingCardHolder DECIMAL(38, 0),
    network STRING,
    amount DECIMAL(38, 2),
    tags STRING,
    gatewaylog DECIMAL(38, 0),
    networkMid STRING,
    lastModifiedTime TIMESTAMP(3),
    mid STRING,
    ca_mallName STRING,
    id DECIMAL(38, 0),
    multiClearCount DECIMAL(38, 0),
    committedUsed DECIMAL(38, 2),
    ca_city STRING,
    responseAmount DECIMAL(38, 2),
    requestAmount DECIMAL(38, 2),
    originalItc STRING,
    extrc STRING,
    date TIMESTAMP(3),
    transmissionDate TIMESTAMP(3),
    completionId DECIMAL(38, 0),
    stan STRING,
    acquirerReferenceId STRING,
    responseCode STRING,
    completionCount DECIMAL(38, 0),
    captureDate DATE,
    reversalId DECIMAL(38, 0),
    expirationTime TIMESTAMP(3),
    fileName STRING,
    ca_zip STRING,
    currencyCode STRING,
    tid STRING,
    settlementDate DATE,
    ca_region STRING,
    acquirerFee DECIMAL(38, 4),
    functionCode STRING,
    ca_country STRING,
    ca_name STRING,
    forwardingInstId STRING,
    approvalNumber STRING,
    incomingNetworkRequestITC STRING,
    adviceId DECIMAL(38, 0),
    reasonCode STRING,
    card DECIMAL(38, 0),
    digitalWalletToken DECIMAL(38, 0),
    feeRate DECIMAL(38, 3),
    additionalAmount DECIMAL(38, 2),
    cardHolder DECIMAL(38, 0),
    subNetwork STRING,
    batchNumber DECIMAL(38, 0),
    originator STRING,
    acquirer STRING,
    itc STRING,
    outstanding DECIMAL(38, 0),
    node STRING,
    duration DECIMAL(38, 0),
    account DECIMAL(38, 0),
    request STRING,
    rc STRING,
    mcc STRING,
    localId DECIMAL(38, 0),
    returnedBalances STRING,
    localTransactionDate TIMESTAMP(3),
    remoteHost STRING,
    ca_storeNumber STRING,
    account2 DECIMAL(38, 0),
    PRIMARY KEY(__jetstream__prg_id, __jetstream__shard_id, id) NOT ENFORCED
) DISTRIBUTED BY HASH(__jetstream__prg_id, __jetstream__shard_id, id) INTO 1 BUCKETS WITH (
    'changelog.mode' = 'upsert',
    'key.avro-registry.schema-context' = '.flink-dev',
    'value.avro-registry.schema-context' = '.flink-dev',
    'key.format' = 'avro-registry',
    'value.format' = 'avro-registry',
    'kafka.retention.time' = '0',
    'kafka.producer.compression.type' = 'snappy',
    'scan.bounded.mode' = 'unbounded',
    'scan.startup.mode' = 'earliest-offset',
    'value.fields-include' = 'all'
);

CREATE TABLE IF NOT EXISTS tranlog (
    __jetstream__prg_id STRING,
    __jetstream__shard_id STRING,
    __jetstream__entry_createdate TIMESTAMP(3),
    __jetstream__deleted BOOLEAN,
    __jetstream__loaded_at TIMESTAMP(3),
    __jetstream__source_ts TIMESTAMP(3),
    __jetstream__transaction_id STRING,
    __jetstream__gtid STRING,
    __jetstream__offset STRING,
    __jetstream__partition INTEGER,
    __jetstream__key STRING,
    __jetstream__ts TIMESTAMP(3),
    __jetstream__total_order INTEGER,
    __jetstream__data_collection_order INTEGER,
    __jetstream__source_name STRING,
    __jetstream__source_db STRING,
    __jetstream__source_table STRING,
    __jetstream__server_uuid STRING,
    __jetstream__server_transaction_id INTEGER,
    __jetstream__op STRING,
    __jetstream__snapshot BOOLEAN,
    ca_street STRING,
    response STRING,
    transactionState STRING,
    reversalCount DECIMAL(38, 0),
    retrievalReferenceNumber STRING,
    irc STRING,
    displayMessage STRING,
    glTransaction DECIMAL(38, 0),
    refId DECIMAL(38, 0),
    networkReferenceId STRING,
    voidCount DECIMAL(38, 0),
    issuerFee DECIMAL(38, 4),
    voidId DECIMAL(38, 0),
    createdTime TIMESTAMP(3),
    actingCardHolder DECIMAL(38, 0),
    network STRING,
    amount DECIMAL(38, 2),
    tags STRING,
    gatewaylog DECIMAL(38, 0),
    networkMid STRING,
    lastModifiedTime TIMESTAMP(3),
    mid STRING,
    ca_mallName STRING,
    id DECIMAL(38, 0),
    multiClearCount DECIMAL(38, 0),
    committedUsed DECIMAL(38, 2),
    ca_city STRING,
    responseAmount DECIMAL(38, 2),
    requestAmount DECIMAL(38, 2),
    originalItc STRING,
    extrc STRING,
    date TIMESTAMP(3),
    transmissionDate TIMESTAMP(3),
    completionId DECIMAL(38, 0),
    stan STRING,
    acquirerReferenceId STRING,
    responseCode STRING,
    completionCount DECIMAL(38, 0),
    captureDate DATE,
    reversalId DECIMAL(38, 0),
    expirationTime TIMESTAMP(3),
    fileName STRING,
    ca_zip STRING,
    currencyCode STRING,
    tid STRING,
    settlementDate DATE,
    ca_region STRING,
    acquirerFee DECIMAL(38, 4),
    functionCode STRING,
    ca_country STRING,
    ca_name STRING,
    forwardingInstId STRING,
    approvalNumber STRING,
    incomingNetworkRequestITC STRING,
    adviceId DECIMAL(38, 0),
    reasonCode STRING,
    card DECIMAL(38, 0),
    digitalWalletToken DECIMAL(38, 0),
    feeRate DECIMAL(38, 3),
    additionalAmount DECIMAL(38, 2),
    cardHolder DECIMAL(38, 0),
    subNetwork STRING,
    batchNumber DECIMAL(38, 0),
    originator STRING,
    acquirer STRING,
    itc STRING,
    outstanding DECIMAL(38, 0),
    node STRING,
    duration DECIMAL(38, 0),
    account DECIMAL(38, 0),
    request STRING,
    rc STRING,
    mcc STRING,
    localId DECIMAL(38, 0),
    returnedBalances STRING,
    localTransactionDate TIMESTAMP(3),
    remoteHost STRING,
    ca_storeNumber STRING,
    account2 DECIMAL(38, 0),
    PRIMARY KEY(__jetstream__prg_id, __jetstream__shard_id, id) NOT ENFORCED
) DISTRIBUTED BY HASH(__jetstream__prg_id, __jetstream__shard_id, id) INTO 1 BUCKETS WITH (
    'changelog.mode' = 'upsert',
    'key.avro-registry.schema-context' = '.flink-dev',
    'value.avro-registry.schema-context' = '.flink-dev',
    'key.format' = 'avro-registry',
    'value.format' = 'avro-registry',
    'kafka.retention.time' = '0',
    'kafka.producer.compression.type' = 'snappy',
    'scan.bounded.mode' = 'unbounded',
    'scan.startup.mode' = 'earliest-offset',
    'value.fields-include' = 'all'
);

CREATE TABLE IF NOT EXISTS cdc_marqeta_jcard_tranlog_history (
    record_content STRING,
    record_metadata STRING
) WITH (
    'connector' = 'kafka',
    'topic' = 'cdc-marqeta-jcard-tranlog-history',
    'properties.bootstrap.servers' = 'localhost:9092',
    'value.format' = 'json-registry',
    'value.json-registry.schema-context' = '.flink-dev',
    'scan.startup.mode' = 'earliest-offset',
    'scan.bounded.mode' = 'unbounded'
);

CREATE TABLE IF NOT EXISTS cdc_marqeta_jcard_uberddl (
    record_content STRING
) WITH (
    'connector' = 'kafka',
    'topic' = 'cdc-marqeta-jcard-uberddl',
    'properties.bootstrap.servers' = 'localhost:9092',
    'value.format' = 'json-registry',
    'value.json-registry.schema-context' = '.flink-dev',
    'scan.startup.mode' = 'earliest-offset',
    'scan.bounded.mode' = 'unbounded'
);

CREATE TABLE IF NOT EXISTS cdc_marqeta_jcard_ddl (
    record_content STRING
) WITH (
    'connector' = 'kafka',
    'topic' = 'cdc-marqeta-jcard-ddl',
    'properties.bootstrap.servers' = 'localhost:9092',
    'value.format' = 'json-registry',
    'value.json-registry.schema-context' = '.flink-dev',
    'scan.startup.mode' = 'earliest-offset',
    'scan.bounded.mode' = 'unbounded'
);

CREATE TABLE IF NOT EXISTS cdc_marqeta_jcard_dbtransaction (
    record_content STRING
) WITH (
    'connector' = 'kafka',
    'topic' = 'cdc-marqeta-jcard-dbtransaction',
    'properties.bootstrap.servers' = 'localhost:9092',
    'value.format' = 'json-registry',
    'value.json-registry.schema-context' = '.flink-dev',
    'scan.startup.mode' = 'earliest-offset',
    'scan.bounded.mode' = 'unbounded'
);

CREATE TABLE IF NOT EXISTS transaction_tracking (
    server_uuid STRING,
    loadable_begin INTEGER,
    loadable_end INTEGER,
    complete_begin INTEGER,
    complete_end INTEGER,
    incomplete_begin INTEGER,
    incomplete_end INTEGER,
    contiguous_begin INTEGER,
    contiguous_end INTEGER,
    noncontiguous_begin INTEGER,
    noncontiguous_end INTEGER,
    old_enough_begin INTEGER,
    old_enough_end INTEGER,
    missing_old_transactions INTEGER,
    overcomplete_transactions INTEGER,
    PRIMARY KEY(server_uuid) NOT ENFORCED
) DISTRIBUTED BY HASH(server_uuid) INTO 1 BUCKETS WITH (
    'changelog.mode' = 'upsert',
    'key.avro-registry.schema-context' = '.flink-dev',
    'value.avro-registry.schema-context' = '.flink-dev',
    'key.format' = 'avro-registry',
    'value.format' = 'avro-registry',
    'kafka.retention.time' = '0',
    'kafka.producer.compression.type' = 'snappy',
    'scan.bounded.mode' = 'unbounded',
    'scan.startup.mode' = 'earliest-offset',
    'value.fields-include' = 'all'
)
