apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flink-estimator

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      app: flink-estimator
      environment: dev

images:
  - name: flink-estimator
    newName: jbcodeforce/flink-estimator
    newTag: latest

replicas:
  - name: flink-estimator
    count: 2 