apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-estimator-pvc
  labels:
    app: flink-estimator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path 