apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: eda-apicurioregistry
spec:
  configuration:
    persistence: "kafka"
    kafka:
      bootstrapServers: "jb-kafka-kafka-bootstrap.kafka-strimzi.svc:9092"